### ISSUE TITLE
Input GUI

### ISSUE THREAD

**Issue by AnnibaleC** [SteveWick/majorProject#2]
Need a GUI that accepts the inputs which will later go on to make the schedule.
Inputs:
- Number of teams
- Number of courts
- Start time
- End time
*Add more if you think we need them.

**Comment by SteveWick** [comment]
IM GONNA HELP YOU ANNIBALE M'DUDE

**Comment by Macaulay155** [comment]
Gotchu Fam.

**Comment by AnnibaleC** [comment]
https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Clyde_The_Bulldog.jpg/220px-Clyde_The_Bulldog.jpg

**Comment by AnnibaleC** [comment]
Text field variable names: teams , courts , start_time , end_time

**Comment by SteveWick** [comment]
public class GetVariable {
	public int teams = GetTeams();
	public int GetTeams(){
		try {
			return Integer.valueOf(InputGui.teams.getText());
		} catch (NumberFormatException e) {
			return 0;
		
	}
	}
	public int GetCourts(){
		try {
			return Integer.valueOf(InputGui.courts.getText());
		} catch (NumberFormatException e) {
			return 0;
		
	}
	}
	public int[] GetStart_Time(){
		try {
			return (Integer.valueOf(InputGui.start_time.getText())).split(":");
		} catch (NumberFormatException e) {
			int[] zero = {0};
			return zero;
		
	}
	}
	public int[] GetEnd_Time(){
		try {
			return (Integer.valueOf(InputGui.end_time.getText())).split(":");
		} catch (NumberFormatException e) {
			int[] zero = {0};
			return zero;
		
	}
	}

}

**Comment by AnnibaleC** [comment]
package Gui;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import javax.swing.JTable;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.GridLayout;
import java.awt.FlowLayout;
import javax.swing.JTextField;
import java.awt.SystemColor;
import java.awt.Color;
import javax.swing.UIManager;

@SuppressWarnings("serial")
public class InputGui extends JFrame {

	private JPanel contentPane;
	private JTable table;
	private JTable table_1;
	public static JTextField teams;
	public static JTextField courts;
	public static JTextField start_time;
	public static JTextField end_time;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					InputGui frame = new InputGui();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public InputGui() {
		setBackground(Color.WHITE);
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 496, 355);
		contentPane = new JPanel();
		contentPane.setBackground(UIManager.getColor("control"));
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(new BorderLayout(0, 0));
		
		JPanel panel = new JPanel();
		panel.setBackground(Color.CYAN);
		contentPane.add(panel, BorderLayout.CENTER);
		panel.setLayout(new GridLayout(2, 1, 0, 0));
		
		JPanel Title_Panel = new JPanel();
		Title_Panel.setBackground(SystemColor.controlHighlight);
		panel.add(Title_Panel);
		Title_Panel.setLayout(null);
		
		JLabel lblKys = new JLabel("Test");
		lblKys.setHorizontalAlignment(SwingConstants.CENTER);
		lblKys.setBounds(131, 0, 204, 36);
		Title_Panel.add(lblKys);
		
		JPanel panel_13 = new JPanel();
		panel_13.setBounds(249, 12, 0, 0);
		Title_Panel.add(panel_13);
		panel_13.setLayout(new GridLayout(1, 0, 0, 0));
		
		JButton btnInsertData = new JButton("Insert data");
		btnInsertData.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				String team = teams.getText();
				int teamnumber = Integer.parseInt(team);
				
				String startoftime = start_time.getText();
				int starttime = Integer.parseInt(startoftime);
				
				String end_min = end_time.getText();
				int endtime = Integer.parseInt(end_min);
				
				String court = courts.getText();
				int courtnumber = Integer.parseInt(court);
				System.out.println(teamnumber + "" +courtnumber  + "" + starttime  + "" + endtime);
			}
		});
		btnInsertData.setBounds(10, 97, 110, 45);
		Title_Panel.add(btnInsertData);
		
		JButton Exit = new JButton("Exit");
		Exit.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				System.exit(0);
			}
		});
		Exit.setBounds(350, 97, 110, 45);
		Title_Panel.add(Exit);
		
		JPanel Middle_panel = new JPanel();
		Middle_panel.setBackground(new Color(240, 240, 240));
		panel.add(Middle_panel);
		Middle_panel.setLayout(new GridLayout(4, 2, 0, 0));
		
		JPanel panel_4 = new JPanel();
		panel_4.setBackground(SystemColor.controlHighlight);
		Middle_panel.add(panel_4);
		
		JLabel lblNumberOfTeams = new JLabel("Number of teams:");
		panel_4.add(lblNumberOfTeams);
		
		JPanel panel_5 = new JPanel();
		panel_5.setBackground(SystemColor.controlHighlight);
		Middle_panel.add(panel_5);
		
		teams = new JTextField();
		teams.setText("");
		panel_5.add(teams);
		teams.setColumns(10);
		
		JPanel panel_6 = new JPanel();
		panel_6.setBackground(SystemColor.controlHighlight);
		Middle_panel.add(panel_6);
		
		JLabel lblNumberOfCourts = new JLabel("Number of courts:");
		panel_6.add(lblNumberOfCourts);
		
		JPanel panel_2 = new JPanel();
		panel_2.setBackground(SystemColor.controlHighlight);
		Middle_panel.add(panel_2);
		
		courts = new JTextField();
		panel_2.add(courts);
		courts.setColumns(10);
		
		JPanel panel_7 = new JPanel();
		panel_7.setBackground(SystemColor.controlHighlight);
		Middle_panel.add(panel_7);
		panel_7.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		
		JLabel lblWhenDoesThe = new JLabel("Start time:");
		panel_7.add(lblWhenDoesThe);
		
		JPanel panel_1 = new JPanel();
		panel_1.setBackground(SystemColor.controlHighlight);
		Middle_panel.add(panel_1);
		
		start_time = new JTextField();
		panel_1.add(start_time);
		start_time.setColumns(10);
		
		JPanel panel_8 = new JPanel();
		panel_8.setBackground(SystemColor.controlHighlight);
		Middle_panel.add(panel_8);
		
		JLabel lblWhenDoesThe_1 = new JLabel("End time\r\n:");
		panel_8.add(lblWhenDoesThe_1);
		
		JPanel panel_10 = new JPanel();
		panel_10.setBackground(SystemColor.controlHighlight);
		Middle_panel.add(panel_10);
		
		end_time = new JTextField();
		panel_10.add(end_time);
		end_time.setColumns(10);
		
	}
}

**Comment by SteveWick** [comment]
*This should fix the problem with the split*

package main;

public class GetVariable {
	public int teams = GetTeams();
	public int courts = GetCourts();
	public int start_time_min = GetStart_Time_Min();
	public int start_time_hr = GetStart_Time_Hr();
	public int end_time_min = GetEnd_Time_Min();
	public int end_time_hr = GetEnd_Time_Hr();

	public int GetTeams(){
		try {
			return Integer.valueOf(InputGui.teams.getText());
		} catch (NumberFormatException e) {
			return 0;
		
	}
	}
	public int GetCourts(){
		try {
			return Integer.valueOf(InputGui.courts.getText());
		} catch (NumberFormatException e) {
			return 0;
		
	}
	}
	public int GetStart_Time_Min(){
		try {
			int[] start_time = InputGui.start_time.getText().split(":");
			return start_time[1];
		} catch (NumberFormatException e) {
			return 99;
		
	}
	}
	public int GetStart_Time_Hr(){
		try {
			int[] start_time = InputGui.start_time.getText().split(":");
			return start_time[0];
		} catch (NumberFormatException e) {
			return 99;
		
	}
	}

	public int GetEnd_Time_Min(){
		try {
			int[] end_time = InputGui.end_time.getText().split(":");
			return end_time[1];
		} catch (NumberFormatException e) {
			return 99;
		
	}
	}
	public int GetEnd_Time_Hr(){
		try {
			int[] end_time = InputGui.end_time.getText().split(":");
			return end_time[0];
		} catch (NumberFormatException e) {
			return 99;
		
	}
	}

}

**Comment by SteveWick** [comment]
System.out.println("Teams: " + teams);
System.out.println("Courts: " + courts);
System.out.println("Start time: " + start_time_hr + ":" + start_time_min);
System.out.println("Endtime: " + end_time_hr + ":" + end_time_min);
System.out.println("Tournament Type: " + InputGui.EliminationPicker.GetSelectedItem(););

**Comment by SteveWick** [comment]
[GetVariable and InputGUI.zip](https://github.com/SteveWick/majorProject/files/709067/GetVariable.and.InputGUI.zip)

**Comment by SteveWick** [comment]
if (GetVariable.GetTeams() == 0) {
					JOptionPane.showMessageDialog(panel, "This is not a correct number of teams.", "Error",
							JOptionPane.ERROR_MESSAGE);
				}
				if (GetVariable.GetCourts() == 0) {
					JOptionPane.showMessageDialog(panel, "This is not a correct number of courts.", "Error",
							JOptionPane.ERROR_MESSAGE);
				}
				if (GetVariable.GetStart_Time_Hr() == 99 || GetVariable.GetStart_Time_Min() == 99) {
					JOptionPane.showMessageDialog(panel, "This is not a correct start time.", "Error",
							JOptionPane.ERROR_MESSAGE);
				}
				if (GetVariable.GetEnd_Time_Hr() == 99 || GetVariable.GetEnd_Time_Min() == 99) {
					JOptionPane.showMessageDialog(panel, "This is not a correct end time.", "Error",
							JOptionPane.ERROR_MESSAGE);
				}

**Comment by AnnibaleC** [comment]
https://gyazo.com/2888c801777aabb6be471934c3c187b4
